social:
  instagram: //instagram.anataborda.com
  facebook: //facebook.anataborda.com
  twitter: //twitter.anataborda.com
  sumup: //anataborda.sumup.link
  etsy: //etsy.anataborda.com
  pinterest: //pinterest.anataborda.com

google_analytics: UA-48440306-10

store_sumup:
  link: https://anataborda.sumup.link

form_order:
  post_url: https://www-contact-335615.uc.r.appspot.com/order/artwork
  title: Contact for new ArtWork Order
  name: Full Name
  email: Email Address
  message: Details about the Artwork you looking to order, dimensions, colours, any reference you have seen in my portfolio

gallery:
  # template: cards
  template: portfolio

nav_links:
  # - title: Home Decor
  #   url: /home-decor-art-resin-and-wall-tapestry-unique-gifts

  # - title: Online Store
  #   url: https://anataborda.sumup.link/
  #   target: _blank

  # - title: Gallery
  #   url: /gallery

  - title: Resin Artwork
    url: /resin-artwork

  - title: Wall Tapestry
    url: /wall-tapestry

  # - title: Events
  #   url: /events

  #- title: Order-Artwork
  #  url: /Order-Artwork

  # - title: portfolio
  #   url: /portfolio

  - title: Social Networks
    url: /social-networks

  - title: About Me
    url: /about-me

site:
  title: Ana Taborda Art
  locale: en_GB
