
baseurl: "/anataborda.com"

url: https://itnov.github.io

title: "Ana Taborda Art, Resin and Wall Tapestry, UK London"

description: "Ana Taborda Art, Resin and Wall Tapestry, UK London"

remote_theme: pages-themes/slate@v0.2.0

plugins:
- jekyll-remote-theme

theme: jekyll-theme-slate

google_analytics: 1234

keep_files: [CNAME, .git]

gems:
- jekyll-github-metadata
- jekyll-redirect-from      

foo: bar

markdown: kramdown

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

collections:
  wall-tapestry:
    output: true  
  resin-artwork:
    output: true  
  gallery:
    output: true
