baseurl: "" # the subpath of your site, e.g. /blog
title: "Ana Taborda Art, Resin and Wall Tapestry, UK London" # the name of your site, e.g. ACME Corp.

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-slate

show_downloads: false
google_analytics: 1234

keep_files: [CNAME, .git]

gems:
- jekyll-github-metadata
- jekyll-redirect-from
- jekyll-sitemap

markdown: kramdown

collections:
  artwork:
    output: true
    permalink: /artwork/:path 
